me="tabRippleColor">@color/m3_tabs_ripple_color</item>
    <item name="tabIndicatorFullWidth">false</item>
    <item name="tabIndicatorAnimationDuration">?attr/motionDurationLong2</item>
    <item name="materialThemeOverlay">@style/ThemeOverlay.Material3.TabLayout</item>
  </style><style name="Base.Widget.Material3.TabLayout.OnSurface" parent="Widget.Material3.TabLayout">
    <item name="android:background">@android:color/transparent</item>
  </style><style name="Base.Widget.Material3.TabLayout.Secondary" parent="Widget.Material3.TabLayout">
    <item name="android:background">@macro/m3_comp_secondary_navigation_tab_container_color</item>
    <item name="tabIconTint">@color/m3_tabs_icon_color_secondary</item>
    <item name="tabTextAppearance">@macro/m3_comp_secondary_navigation_tab_label_text_type</item>
    <item name="tabTextColor">@color/m3_tabs_text_color_secondary</item>
    <item name="tabIndicator">@drawable/m3_tabs_line_indicator</item>
    <item name="tabIndicatorColor">@macro/m3_comp_secondary_navigation_tab_active_indicator_color</item>
    <item name="tabRippleColor">@color/m3_tabs_ripple_color_secondary</item>
    <item name="tabIndicatorFullWidth">true</item>
  </st